### ISSUE TITLE
Breaks Wiki Preview functionality on Trac 1.2

### ISSUE THREAD

**Issue by TerjeMjelde** [trac-hacks/trac-readme-plugin#1]
The Wiki preview functionality is broken when this plugin is installed, at least on Trac 1.2. The preview box appears but it is empty.

**Comment by rjollos** [comment]
Do you mean Trac 1.2? There is no Trac 1.12 yet.

**Comment by TerjeMjelde** [comment]
Ah, stupid me :) I meant Trac 1.2.

**Comment by johneegeek** [comment]
I see the same behavior using Trac 1.1.6
