### ISSUE TITLE
Breaks rendering of files in repo browser

### ISSUE THREAD

**Issue by arr-dev** [trac-hacks/trac-readme-plugin#2]
File contents in repo browser are not rendered when this plugin is enabled.

It's loaded, but `table.code` is deleted from DOM.

It doesn't matter which file type is loaded, none are rendered except markdown.

Trac version is `1.2.2`

**Comment by arr-dev** [comment]
It seems that adding a check around [readme_renderer/htdocs/readme.js#L3](https://github.com/trac-hacks/trac-readme-plugin/blob/master/readme_renderer/htdocs/readme.js#L3) to make sure that `$(this).children('pre')` is present should do the trick

**Comment by rjollos** [comment]
Similar behavior was reported [here](https://groups.google.com/d/msg/trac-users/qnDf_TADbcI/nhCnJaF5AwAJ).

**Comment by rjollos** [comment]
I made a pull request: #3. Could you please test?
